version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - lukesaltweather
  ignore:
  - dependency-name: boto3
    versions:
    - 1.17.45
    - 1.17.47
